name: multacc
description: multiple accounts

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.2
  dbutils: ^1.0.0
  path:
  hive: ^1.0.0
  hive_flutter: ^0.3.0
  path_provider: ^1.3.0
 
  # UI
  cupertino_icons: any
  flutter_statusbarcolor : any
  google_fonts: any
  flutter_brand_icons: any
  flutter_svg: any

  # device APIs
  contacts_service: any
  permission_handler: any
  url_launcher: any
  shared_preferences: any

  # state management / data
  provider: any
  rxdart: any
  mobx: any
  flutter_mobx: any
  mobx_codegen: any
  get_it: any

  http: any
  intl: any

  # firebase APIs
  google_sign_in: any
  firebase_auth: any
  firebase_dynamic_links: any

dev_dependencies:
  build_runner: ^1.8.0
  hive_generator: ^0.7.0

  flutter_test:
    sdk: flutter

  flutter_launcher_icons: any

# generate app icons using `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#303030"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
          style: italic
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700
